### PR TITLE
fix #166, issues when resizing sometimes causes text-selection in som…

### LINKED ISSUE #166: Text select while resizing in IE11
I'm using re-resizable 4.1.1

Bug appears in IE11.
I can't provide reproduced project on webpackbin, cos webpackbin doesn't work in my IE11.

When I drag resize handle, the text around became seleted sometimes.
In my case, this bug appears with complext layout, when animation framerate slows down.

I solved that by adding "-ms-user-select: none; user-select: none;" to handle style;  
"user-select: none" just for safity.

### PR DESCRIPTION
**Pull request by hbogs**
…e browsers

### Proposed solution
Fixes #166. I also noticed this behavior from time to time on both Firefox and Chrome on Windows.
The fix creates an invisible overlay that covers the entire page, while resizing the element. When resizing stops, the invisible overlay is removed. The cursor for the overlay is set to the same cursor as the handle that initiated the drag so it should not be visible to the user that this overlay is created.

### Tradeoffs
Not sure if there are any? z-index might not be high enough to cover all cases maybe?

### Testing Done
I have done manual testing only, as I cannot get the automated tests to run.

### CODE REVIEW

**Comment by bokuweb** [comment]
@hbogs Thanks for your PR!! 
Do you know which browser needs this workaround ?( only IE11 ?)

**Comment by hbogs** [comment]
It is definitely most noticeable in IE11 - seems to happen more often there. I did also notice problems in both Chrome and Firefox (on Windows 10 . not tested on mac/linux) when resizing complex items (a container that has many nested items for example) - so I think it applies to all browsers.

File: src/index.js [hunk 1]
```diff
@@ -153,6 +153,35 @@ const definedProps = [
...
+    position: fixed;
+    z-index: 9999;
+    top: 0;
+    left: 0;
+    bottom: 0;
+    right: 0;`;
+  if (body) {
+    body.appendChild(resizeOverlay);
+  }
+};
```
Comment (bokuweb) [inline src/index.js]: I think that it is better to do as follows. what do you think about it?

```
<div
        ref={(c: React.ElementRef<'div'> | null) => { this.resizable = c; }}
        style={{
          position: 'relative',
          ...userSelect,
          ...this.props.style,
          ...this.sizeStyle,
          maxWidth: this.props.maxWidth,
          maxHeight: this.props.maxHeight,
          minWidth: this.props.minWidth,
          minHeight: this.props.minHeight,
          boxSizing: 'border-box',
        }}
        className={this.props.className}
        {...this.extendsProps}
      >
        <div
           style={{
              ...some overlay styles...
              display: this.state.isResizing ? 'block' : 'none',
            }} 
        />
        {this.props.children}
        {this.renderResizer()}
      </div>
```

Comment (hbogs) [reply src/index.js]: Interesting :) This seems like a better approach.

I dont like rendering stuff that gets display none though - what about changing it to this:
```
{this.state.isResizing  &&
        <div
           style={{
              ...some overlay styles...
            }} 
        />}
```

to avoid rendering the resize-div when it is not needed. WDYT?

Comment (bokuweb) [reply src/index.js]: Looks Good :)

**Comment by hbogs** [comment]
@bokuweb I updated the PR, please have another look :)

File: src/index.js [hunk 2]
```diff
@@ -605,6 +574,24 @@ export default class Resizable extends React.Component<ResizableProps, State> {
...
       >
+        {this.state.isResizing &&
+        <div
+          style={{
+            height: '100%',
+            width: '100%',
+            backgroundColor: 'rgba(0,0,0,0)',
+            cursor: `${this.state.resizeCursor || 'auto'}`,
+            opacity: '0',
+            position: 'fixed',
```
Comment (bokuweb) [inline src/index.js]: [question] Why use `fixed` instead of `absolute`?

Comment (hbogs) [reply src/index.js]: Since we want this div to cover the entire viewport, it makes sense to use fixed. Fixed position is relative to the viewport, and setting the width and height to 100% will then make it cover the entire screen.

**Comment by bokuweb** [comment]
@hbogs Thanks :)

**Comment by bokuweb** [comment]
@hbogs v4.3.2 published 🎉
